# PROTOTYPE — delete after #386. Mechanical inliner: does the ./assets/ stylesheet
# survive as a build step when the render target can't fetch siblings?
import re, pathlib
src  = pathlib.Path('01-the-placement-litmus.html').read_text()
css  = pathlib.Path('assets/lesson.css').read_text()
out  = re.sub(r'\s*<link rel="stylesheet" href="\./assets/lesson\.css">',
              '\n<style>\n' + css + '</style>', src)
out  = out.replace('Variant A: D23-faithful. Shared stylesheet lives in ./assets/, linked externally.',
                   'Variant B: generated by inline.py — same lesson, ./assets/ stylesheet inlined.')
pathlib.Path('01-the-placement-litmus.inlined.html').write_text(out)
print('wrote 01-the-placement-litmus.inlined.html', len(out), 'bytes; link removed:', '<link' not in out)
