#!/usr/bin/env node
// merge-quiz.mjs — the pre-merge comprehension observer (PreToolUse: Bash) for
// adr:harness-loop-instrumentation (H8), STAGE A.
//
// THE PROBLEM IT MEASURES. In a fleet where an agent writes most of the code, the thing
// that silently decays is not correctness — tests cover that — it is the operator's own
// understanding of what shipped. Simon Willison calls the accumulated version "cognitive
// debt". A diff shows lines changed; it does not show what you understood. Nothing else
// in the harness set measures that, and by construction you cannot notice it yourself.
//
// ── STAGE A IS OBSERVE-ONLY. IT MUST NOT BLOCK. ──
//
// ADR-0086 forbids shipping an enforcing control straight to Operational. So this stage
// records what a gate WOULD have caught and changes nothing:
//
//   Stage A (here)  — record every merge, its size, and whether a quiz would have fired.
//   Stage B (later) — same detector blocks and runs the quiz, promoted on Stage A data
//                     via a RIDM decision, NOT on the strength of the idea.
//
// THE RETIREMENT RULE, and it is a real rule: if Stage A shows the quiz would never have
// blocked across ~20 merges, H8 is RETIRED, not promoted. A harness whose human_delta is
// zero is theatre with a log file. Retiring it is the loop working, not the loop failing.
//
// ── WHEN STAGE B IS BUILT, THE ANTI-HACK IS NON-NEGOTIABLE ──
//
// The quiz MUST be generated by a session that did NOT write the code, from the diff and
// the spec, running as a subagent with NO Write/Edit tools. An implementer that writes its
// own quiz asks about what it did, not about what matters — it reliably tests the parts it
// is most confident about, which converts a comprehension gate into a rubber stamp. This is
// textbook self-preference bias (Panickssery et al. 2024; arXiv:2410.21819), and Anthropic's
// own guidance is explicit that a fresh context improves review "since Claude won't be
// biased toward code it just wrote". The two-agent relay already provides the separation.
//
// SHADOW-FIRST (ADR-0086). Fails open, always exits 0, emits no permission decision.
//
// Usage:
//   node scripts/hooks/merge-quiz.mjs            # PreToolUse(Bash) hook, input on stdin
//   node scripts/hooks/merge-quiz.mjs --report   # Stage A verdict: promote, keep observing, or retire

import { readFileSync, existsSync, appendFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';

/** Diff size at or above which Stage B would fire a quiz. Tunable on Stage A evidence. */
export const QUIZ_THRESHOLD_LINES = 150;

const expand = (p) => (p && p.startsWith('~') ? p.replace('~', homedir()) : p);

/**
 * Is this shell command a merge that crosses the review boundary? PURE.
 *
 * Deliberately narrow. `git merge --abort`, `--continue`, `--quit` are not merges crossing
 * the boundary, and `gh pr merge` variants all count. Matching too broadly here would flood
 * the ledger with non-events and make the Stage A verdict meaningless.
 *
 * @param {string} command
 * @returns {{isMerge:boolean, kind?:'gh-pr'|'git', pr?:string}}
 */
export function classifyMergeCommand(command) {
  if (!command || typeof command !== 'string') return { isMerge: false };
  // Consider each segment of a compound command separately.
  for (const raw of command.split(/&&|\|\||;|\n/)) {
    const seg = raw.trim();
    const gh = /(^|\s)gh\s+pr\s+merge(\s|$)/.exec(seg);
    if (gh) {
      const pr = /(?:^|\s)(?:gh\s+pr\s+merge)\s+(\d+)/.exec(seg);
      return { isMerge: true, kind: 'gh-pr', pr: pr?.[1] };
    }
    const git = /(^|\s)git\s+merge(\s|$)/.exec(seg);
    if (git) {
      if (/--(abort|continue|quit)\b/.test(seg)) continue; // not a boundary crossing
      return { isMerge: true, kind: 'git' };
    }
  }
  return { isMerge: false };
}

/**
 * Would Stage B have fired a quiz for a change of this size? PURE.
 *
 * Returns `null` — NOT false — when the size could not be determined. That distinction is
 * load-bearing: `stageAVerdict` excludes unknown-size rows from its sample entirely. If they
 * were counted as `false` they would pad `merges` (the denominator of the 20-merge minimum)
 * while never being able to reach `wouldHave`, so every unmeasurable merge would push the
 * verdict toward `retire` — manufacturing evidence that the gate is useless out of nothing
 * but a missing merge-base.
 */
export function wouldQuiz(changedLines, threshold = QUIZ_THRESHOLD_LINES) {
  if (typeof changedLines !== 'number' || !Number.isFinite(changedLines)) return null;
  return changedLines >= threshold;
}

/**
 * Rolling comprehension by (repo × domain) — the heatmap. PURE.
 *
 * This is the number the whole harness exists to produce. It answers a question you cannot
 * answer by introspection: is my understanding of a subsystem holding, or quietly decaying
 * while the agent keeps shipping into it? A falling cell is the signal to re-engage before
 * the debt compounds.
 *
 * EWMA, not a flat mean: recent merges should dominate. A repo you understood well six
 * months ago tells you nothing about the code that landed last week.
 *
 * `mode` is part of the cell key and must stay that way. A `taught` score (the change
 * was briefed first) answers "can you understand this when walked through it"; a `cold`
 * score answers "did you already understand it". Averaging them answers neither, and
 * since briefing reliably raises the score, mixing them lets taught runs mask real decay.
 */
export function comprehensionByCell(records, { alpha = 0.4 } = {}) {
  const cells = new Map();
  for (const r of records) {
    if (r?.event !== 'harness:quiz-taken' || typeof r.score !== 'number') continue;
    const repo = r.repo ?? '?';
    const domain = r.domain ?? 'general';
    // Unlabelled legacy rows read as `taught` — the conservative call, since reading
    // an unknown score as cold would overstate demonstrated prior understanding.
    const mode = r.mode === 'cold' ? 'cold' : 'taught';
    const key = `${repo}|${domain}|${mode}`;
    const prev = cells.get(key);
    cells.set(key, {
      repo,
      domain,
      mode,
      ewma: prev ? alpha * r.score + (1 - alpha) * prev.ewma : r.score,
      n: (prev?.n ?? 0) + 1,
      last: r.score,
    });
  }
  return [...cells.values()].sort((a, b) => a.ewma - b.ewma);
}

/**
 * The Stage A verdict. PURE — this is the promotion/retirement decision, computed from
 * evidence rather than from enthusiasm.
 *
 * @param {Array<{would_quiz:boolean}>} records
 * @param {{minMerges?:number}} opts
 */
export function stageAVerdict(records, { minMerges = 20 } = {}) {
  const all = records.filter((r) => r?.event === 'harness:merge-observed');
  // Rows whose diff size was undeterminable cannot discriminate, so they are NOT part of the
  // sample. Counting them would bias every verdict toward `retire` (see wouldQuiz).
  const merges = all.filter((r) => r.would_quiz === true || r.would_quiz === false);
  const unknown = all.length - merges.length;
  const wouldHave = merges.filter((r) => r.would_quiz === true).length;
  const base = { merges: merges.length, wouldHave, unknown };
  if (merges.length < minMerges) {
    return { verdict: 'keep-observing', ...base, needed: minMerges - merges.length };
  }
  if (wouldHave === 0) {
    return { verdict: 'retire', ...base, reason: 'the quiz would never have fired — no evidence it does anything' };
  }
  return { verdict: 'promote-candidate', ...base, reason: 'enough merges would have been gated to justify a RIDM promotion decision' };
}

// ─────────────────────────── I/O boundary ───────────────────────────

function readJsonl(path) {
  if (!existsSync(path)) return [];
  const out = [];
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line));
    } catch {
      /* torn line never kills the pass */
    }
  }
  return out;
}

const git = (args, cwd) => {
  try {
    return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
};

/**
 * Changed-line count for the change actually being merged.
 *
 * For `gh pr merge <N>` this MUST come from the PR, not from the working tree. The first cut
 * measured `merge-base HEAD origin/main` in the hook's cwd, which is only the right answer
 * when the operator happens to be standing on the PR branch. Merging from `main` — the normal
 * case when merging someone else's PR, or after abandoning a `gh pr checkout` — made the diff
 * empty, so a 1000-line PR recorded as `changed_lines: 0`. Every such row pushed the Stage A
 * verdict toward `retire`. (Found by the /merge-quiz fresh-context pass on PR #295.)
 */
function changedLines(cwd, verdict) {
  const head = git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd);

  if (verdict?.kind === 'gh-pr') {
    // Ask GitHub what the PR contains. Networked and ~1s, but this path only runs on an
    // actual merge command, which is rare — correctness is worth far more than the latency
    // here, and the bash prefilter already keeps this off the common path.
    const args = ['pr', 'view', ...(verdict.pr ? [verdict.pr] : []), '--json', 'additions,deletions'];
    try {
      const out = execFileSync('gh', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], timeout: 10_000 });
      const j = JSON.parse(out);
      if (typeof j.additions === 'number' && typeof j.deletions === 'number') {
        return { lines: j.additions + j.deletions, head, source: 'gh-pr' };
      }
    } catch {
      /* offline, unauthenticated, or no such PR → fall through to unknown, never to 0 */
    }
    return { lines: null, head, source: 'gh-pr-unavailable' };
  }

  let base = '';
  for (const cand of ['origin/main', 'main', 'origin/master', 'master']) {
    base = git(['merge-base', 'HEAD', cand], cwd);
    if (base) break;
  }
  if (!base) return { lines: null, head, source: 'no-merge-base' };
  const stat = git(['diff', '--shortstat', `${base}...HEAD`], cwd);
  const ins = /(\d+) insertion/.exec(stat);
  const del = /(\d+) deletion/.exec(stat);
  if (!ins && !del) return { lines: 0, head, source: 'git-diff' };
  return { lines: Number(ins?.[1] ?? 0) + Number(del?.[1] ?? 0), head, source: 'git-diff' };
}

function parseArgs(argv) {
  const args = {};
  for (const a of argv.slice(2)) {
    const m = /^--([^=]+)(?:=(.*))?$/.exec(a);
    if (m) args[m[1]] = m[2] ?? true;
  }
  return args;
}

async function readStdin() {
  if (process.stdin.isTTY) return '';
  const chunks = [];
  for await (const c of process.stdin) chunks.push(c);
  return Buffer.concat(chunks).toString('utf8');
}

async function main() {
  const args = parseArgs(process.argv);
  const ledgerRoot = expand(args['ledger-root'] ?? '~/selfco/tracking');
  const outPath = expand(args.out ?? join(ledgerRoot, 'merge-observations.jsonl'));

  // --record: written by the /merge-quiz SKILL after the human takes the quiz. The hook
  // --capture: deposit what was LEARNED into the selfco vault's append-only ledger, for
  // `/vault sync` to fold into concept/entity pages later. Same seam vault-session.sh uses
  // (wiki/log.md), same discipline: this script owns the deterministic framing and provenance
  // stamp; the body is composed by the skill, because only the skill knows what was explained.
  //
  // WHAT GETS DEPOSITED IS THE GAP, NOT THE TRANSCRIPT. A quiz answered perfectly has nothing
  // to teach later — depositing it would bulk the vault with confirmations of what the operator
  // already knew, which is how a knowledge base turns into a log nobody reads. The deposit is
  // the mechanism they did NOT know plus the explanation that closed it.
  if (args.capture) {
    const vault = expand(process.env.SELFCO_VAULT ?? '~/selfco');
    const logPath = join(vault, 'wiki', 'log.md');
    if (!existsSync(logPath)) {
      console.error(`[merge-quiz] no vault ledger at ${logPath} — nothing captured (run /vault init)`);
      return; // silent no-op like vault-session.sh; never a hard failure
    }
    const body = readFileSync(0, 'utf8').trim(); // the skill composes this on stdin
    if (!body) {
      console.error('[merge-quiz] --capture needs the learning block on stdin; nothing written');
      return;
    }
    const today = new Date().toISOString().slice(0, 10);
    const repo = args.repo ?? basename(resolve(process.cwd()));
    const head = `\n## [${today}] quiz-capture | ${repo}${args.pr ? ` PR#${args.pr}` : ''}\n`;
    const prov = `- harness=merge-quiz · mode=${args.mode === 'cold' ? 'cold' : 'taught'} · score=${args.score ?? '?'} · domain=${args.domain ?? 'general'}\n\n`;
    appendFileSync(logPath, `${head}${prov}${body}\n`);
    console.error(`[merge-quiz] captured to ${logPath} — run /vault sync to fold it into pages`);
    return;
  }

  // observes; the skill quizzes. Same harness, same ledger, two faces.
  if (args.record) {
    const score = Number(args.score);
    if (!Number.isFinite(score) || score < 0 || score > 100) {
      console.error('[merge-quiz] --record needs --score=<0-100>');
      process.exitCode = 1;
      return;
    }
    mkdirSync(dirname(outPath), { recursive: true });
    appendFileSync(
      outPath,
      `${JSON.stringify({
        ts: new Date().toISOString(),
        event: 'harness:quiz-taken',
        harness: 'merge-quiz',
        repo: args.repo ?? basename(resolve(process.cwd())),
        domain: args.domain ?? 'general',
        // taught = the change was briefed first (Step 2); cold = it wasn't. Never merged.
        mode: args.mode === 'cold' ? 'cold' : 'taught',
        pr: args.pr ?? null,
        score,
        questions: Number(args.questions ?? 0) || null,
        // human_delta — did taking the quiz actually change anything? The field that
        // separates a working loop from theatre. A harness whose human_delta stays near
        // zero over ~30 runs is retired, not celebrated.
        human_delta: args['human-delta'] === true || args['human-delta'] === 'true',
      })}\n`,
    );
    console.error(`[merge-quiz] recorded quiz: ${score}/100`);
    return;
  }

  if (args.report) {
    const records = readJsonl(outPath);
    const v = stageAVerdict(records, { minMerges: Number(args['min-merges'] ?? 20) });
    const cells = comprehensionByCell(records);
    if (args.json) {
      console.log(JSON.stringify({ ...v, comprehension: cells }, null, 2));
      return;
    }
    console.log(`[merge-quiz] Stage A: ${v.merges} merge(s) observed, ${v.wouldHave} would have been quizzed.`);
    if (v.verdict === 'keep-observing') console.log(`  → keep observing (${v.needed} more merges before the call).`);
    if (v.verdict === 'retire') console.log(`  → RETIRE H8: ${v.reason}`);
    if (v.verdict === 'promote-candidate') console.log(`  → promotion candidate: ${v.reason}`);
    if (cells.length) {
      console.log('\n  comprehension heatmap (worst first — a falling cell is where to re-engage):');
      for (const c of cells)
        console.log(`    ${String(Math.round(c.ewma)).padStart(3)}  ${c.repo}/${c.domain}  [${c.mode}]  (n=${c.n}, last ${c.last})`);
    } else {
      console.log('\n  no quizzes taken yet — run /merge-quiz before a merge to start the heatmap.');
    }
    return;
  }

  let payload = {};
  try {
    payload = JSON.parse(await readStdin()) ?? {};
  } catch {
    return; // unparseable stdin → allow, record nothing
  }

  const command = payload?.tool_input?.command ?? '';
  const verdict = classifyMergeCommand(command);
  if (!verdict.isMerge) return; // not a merge — silent, allow

  const cwd = payload?.cwd ?? process.cwd();
  const { lines, head, source } = changedLines(cwd, verdict);

  mkdirSync(dirname(outPath), { recursive: true });
  appendFileSync(
    outPath,
    `${JSON.stringify({
      ts: new Date().toISOString(),
      event: 'harness:merge-observed',
      mode: 'shadow',
      harness: 'merge-quiz',
      stage: 'A',
      repo: basename(resolve(cwd)),
      session_id: payload?.session_id ?? null,
      branch: head || null,
      kind: verdict.kind,
      pr: verdict.pr ?? null,
      changed_lines: lines,
      size_source: source, // gh-pr | git-diff | gh-pr-unavailable | no-merge-base
      would_quiz: wouldQuiz(lines), // null when undeterminable — excluded from the verdict sample
      threshold: QUIZ_THRESHOLD_LINES,
      quizzed: false, // Stage A never quizzes — this field is what Stage B flips
    })}\n`,
  );
  // Observe-only: no permissionDecision, no stderr noise, no block.
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]).endsWith('merge-quiz.mjs');
if (invokedDirectly) {
  main().catch(() => {
    /* fail open — a measurement never blocks a merge */
  });
}
