#!/usr/bin/env node
// merge-quiz.mjs — the pre-merge comprehension observer (PreToolUse: Bash) for
// adr:harness-loop-instrumentation (H8), STAGE A.
//
// THE PROBLEM IT MEASURES. In a fleet where an agent writes most of the code, the thing
// that silently decays is not correctness — tests cover that — it is the operator's own
// understanding of what shipped. Simon Willison calls the accumulated version "cognitive
// debt". A diff shows lines changed; it does not show what you understood. Nothing else
// in the harness set measures that, and by construction you cannot notice it yourself.
//
// ── STAGE A IS OBSERVE-ONLY. IT MUST NOT BLOCK. ──
//
// ADR-0086 forbids shipping an enforcing control straight to Operational. So this stage
// records what a gate WOULD have caught and changes nothing:
//
//   Stage A (here)  — record every merge, its size, and whether a quiz would have fired.
//   Stage B (later) — same detector blocks and runs the quiz, promoted on Stage A data
//                     via a RIDM decision, NOT on the strength of the idea.
//
// THE RETIREMENT RULE, and it is a real rule: if Stage A shows the quiz would never have
// blocked across ~20 merges, H8 is RETIRED, not promoted. A harness whose human_delta is
// zero is theatre with a log file. Retiring it is the loop working, not the loop failing.
//
// ── WHEN STAGE B IS BUILT, THE ANTI-HACK IS NON-NEGOTIABLE ──
//
// The quiz MUST be generated by a session that did NOT write the code, from the diff and
// the spec, running as a subagent with NO Write/Edit tools. An implementer that writes its
// own quiz asks about what it did, not about what matters — it reliably tests the parts it
// is most confident about, which converts a comprehension gate into a rubber stamp. This is
// textbook self-preference bias (Panickssery et al. 2024; arXiv:2410.21819), and Anthropic's
// own guidance is explicit that a fresh context improves review "since Claude won't be
// biased toward code it just wrote". The two-agent relay already provides the separation.
//
// SHADOW-FIRST (ADR-0086). Fails open, always exits 0, emits no permission decision.
//
// Usage:
//   node scripts/hooks/merge-quiz.mjs            # PreToolUse(Bash) hook, input on stdin
//   node scripts/hooks/merge-quiz.mjs --report   # Stage A verdict: promote, keep observing, or retire

import { readFileSync, existsSync, appendFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';

/** Diff size at or above which Stage B would fire a quiz. Tunable on Stage A evidence. */
export const QUIZ_THRESHOLD_LINES = 150;

const expand = (p) => (p && p.startsWith('~') ? p.replace('~', homedir()) : p);

/**
 * Is this shell command a merge that crosses the review boundary? PURE.
 *
 * Deliberately narrow. `git merge --abort`, `--continue`, `--quit` are not merges crossing
 * the boundary, and `gh pr merge` variants all count. Matching too broadly here would flood
 * the ledger with non-events and make the Stage A verdict meaningless.
 *
 * @param {string} command
 * @returns {{isMerge:boolean, kind?:'gh-pr'|'git', pr?:string}}
 */
export function classifyMergeCommand(command) {
  if (!command || typeof command !== 'string') return { isMerge: false };
  // Consider each segment of a compound command separately.
  for (const raw of command.split(/&&|\|\||;|\n/)) {
    const seg = raw.trim();
    const gh = /(^|\s)gh\s+pr\s+merge(\s|$)/.exec(seg);
    if (gh) {
      const pr = /(?:^|\s)(?:gh\s+pr\s+merge)\s+(\d+)/.exec(seg);
      return { isMerge: true, kind: 'gh-pr', pr: pr?.[1] };
    }
    const git = /(^|\s)git\s+merge(\s|$)/.exec(seg);
    if (git) {
      if (/--(abort|continue|quit)\b/.test(seg)) continue; // not a boundary crossing
      return { isMerge: true, kind: 'git' };
    }
  }
  return { isMerge: false };
}

/** Would Stage B have fired a quiz for a change of this size? PURE. */
export function wouldQuiz(changedLines, threshold = QUIZ_THRESHOLD_LINES) {
  return typeof changedLines === 'number' && changedLines >= threshold;
}

/**
 * The Stage A verdict. PURE — this is the promotion/retirement decision, computed from
 * evidence rather than from enthusiasm.
 *
 * @param {Array<{would_quiz:boolean}>} records
 * @param {{minMerges?:number}} opts
 */
export function stageAVerdict(records, { minMerges = 20 } = {}) {
  const merges = records.filter((r) => r?.event === 'harness:merge-observed');
  const wouldHave = merges.filter((r) => r.would_quiz).length;
  if (merges.length < minMerges) {
    return { verdict: 'keep-observing', merges: merges.length, wouldHave, needed: minMerges - merges.length };
  }
  if (wouldHave === 0) {
    return { verdict: 'retire', merges: merges.length, wouldHave, reason: 'the quiz would never have fired — no evidence it does anything' };
  }
  return { verdict: 'promote-candidate', merges: merges.length, wouldHave, reason: 'enough merges would have been gated to justify a RIDM promotion decision' };
}

// ─────────────────────────── I/O boundary ───────────────────────────

function readJsonl(path) {
  if (!existsSync(path)) return [];
  const out = [];
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line));
    } catch {
      /* torn line never kills the pass */
    }
  }
  return out;
}

const git = (args, cwd) => {
  try {
    return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
};

/** Changed-line count for the current branch vs its merge-base with the default branch. */
function changedLines(cwd) {
  const head = git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd);
  let base = '';
  for (const cand of ['origin/main', 'main', 'origin/master', 'master']) {
    base = git(['merge-base', 'HEAD', cand], cwd);
    if (base) break;
  }
  if (!base) return { lines: null, head };
  const stat = git(['diff', '--shortstat', `${base}...HEAD`], cwd);
  const ins = /(\d+) insertion/.exec(stat);
  const del = /(\d+) deletion/.exec(stat);
  if (!ins && !del) return { lines: 0, head };
  return { lines: Number(ins?.[1] ?? 0) + Number(del?.[1] ?? 0), head };
}

function parseArgs(argv) {
  const args = {};
  for (const a of argv.slice(2)) {
    const m = /^--([^=]+)(?:=(.*))?$/.exec(a);
    if (m) args[m[1]] = m[2] ?? true;
  }
  return args;
}

async function readStdin() {
  if (process.stdin.isTTY) return '';
  const chunks = [];
  for await (const c of process.stdin) chunks.push(c);
  return Buffer.concat(chunks).toString('utf8');
}

async function main() {
  const args = parseArgs(process.argv);
  const ledgerRoot = expand(args['ledger-root'] ?? '~/selfco/tracking');
  const outPath = expand(args.out ?? join(ledgerRoot, 'merge-observations.jsonl'));

  if (args.report) {
    const v = stageAVerdict(readJsonl(outPath), { minMerges: Number(args['min-merges'] ?? 20) });
    if (args.json) {
      console.log(JSON.stringify(v, null, 2));
      return;
    }
    console.log(`[merge-quiz] Stage A: ${v.merges} merge(s) observed, ${v.wouldHave} would have been quizzed.`);
    if (v.verdict === 'keep-observing') console.log(`  → keep observing (${v.needed} more merges before the call).`);
    if (v.verdict === 'retire') console.log(`  → RETIRE H8: ${v.reason}`);
    if (v.verdict === 'promote-candidate') console.log(`  → promotion candidate: ${v.reason}`);
    return;
  }

  let payload = {};
  try {
    payload = JSON.parse(await readStdin()) ?? {};
  } catch {
    return; // unparseable stdin → allow, record nothing
  }

  const command = payload?.tool_input?.command ?? '';
  const verdict = classifyMergeCommand(command);
  if (!verdict.isMerge) return; // not a merge — silent, allow

  const cwd = payload?.cwd ?? process.cwd();
  const { lines, head } = changedLines(cwd);

  mkdirSync(dirname(outPath), { recursive: true });
  appendFileSync(
    outPath,
    `${JSON.stringify({
      ts: new Date().toISOString(),
      event: 'harness:merge-observed',
      mode: 'shadow',
      harness: 'merge-quiz',
      stage: 'A',
      repo: basename(resolve(cwd)),
      session_id: payload?.session_id ?? null,
      branch: head || null,
      kind: verdict.kind,
      pr: verdict.pr ?? null,
      changed_lines: lines,
      would_quiz: wouldQuiz(lines),
      threshold: QUIZ_THRESHOLD_LINES,
      quizzed: false, // Stage A never quizzes — this field is what Stage B flips
    })}\n`,
  );
  // Observe-only: no permissionDecision, no stderr noise, no block.
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]).endsWith('merge-quiz.mjs');
if (invokedDirectly) {
  main().catch(() => {
    /* fail open — a measurement never blocks a merge */
  });
}
